
spring:
  datasource:
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
  jpa:
    generate-ddl: false


---

spring:
  config.activate.on-profile: dev
  h2:
    console.enabled: true

logging:
  level:
    com.kameo.hospitalservice: DEBUG
